[package]
name = "otel-oom-debug"
version = "0.1.0"
edition = "2024"

[dependencies]
opentelemetry = "0.28"
opentelemetry_sdk = { version = "0.28", features = ["rt-tokio-current-thread", "experimental_trace_batch_span_processor_with_async_runtime", "rt-tokio"] }
opentelemetry-otlp = { version = "0.28", features = ["grpc-tonic", "trace"] }
tracing = "0.1"
tracing-opentelemetry = { version = "0.29", default-features = false }
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.19"